FROM python:3.13

# environment
ENV DATABASE_URL="sqlite+aiosqlite:///./app.db"

# pip
RUN python3 -m pip install --upgrade pip

# app folder
WORKDIR /app

# install app
COPY requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# copy app
COPY . .

# expose ports
EXPOSE 8000

# entrypoint
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
